### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by hcharley** [driescroons/graphql-fields-to-relations#1]
```
/node_modules/graphql-fields-to-relations/lib/index.js:14
            if (parent.slice(!options.root ? 0 : options.root?.split('.').length).length > 0 &&
                                                              ^
```

**Comment by hcharley** [comment]
<img width="735" alt="Screen Shot 2020-12-26 at 10 49 29 PM" src="https://user-images.githubusercontent.com/1542740/103163499-a4e05d80-47cc-11eb-9c94-746aeb720e5b.png">

**Comment by dodiameer** [comment]
It seems like you're using a version of node that doesn't support optional chaining. You can bundle your code using Webpack or Rollup to fix the issue, or upgrade Node to support this feature if possible. As far as I know if you're using Typescript it should also take care of this issue for you.

[Webpack documentation](https://webpack.js.org/guides/getting-started/)  
[Rollup documentation](https://rollupjs.org/guide/en/)
